# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import smsverification.models
import smsverification.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('phone', models.CharField(max_length=20, validators=[smsverification.validators.validate_phone_number])),
                ('code', models.CharField(default=smsverification.models.generate_verification_code, max_length=8)),
                ('verification_date', models.DateTimeField(default=None, blank=True, null=True)),
                ('expiration_date', models.DateTimeField(default=smsverification.models.generate_expiration_date)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
