import {API_BASE_URL} from './constants';

export const URLS = {
    login:                      API_BASE_URL + "login/",
    resetPassword:              API_BASE_URL + "password/reset/",
    resetPasswordConfirm:       API_BASE_URL + "password/reset/confirm/",
    refreshToken:               API_BASE_URL + "token-refresh/",
    countries:                  API_BASE_URL + "countries/",
    regions:                    API_BASE_URL + "regions/",
    cities:                     API_BASE_URL + "cities/",
    zones:                      API_BASE_URL + "zones/",
    facebook:                   API_BASE_URL + "facebook/",
    upload:                     API_BASE_URL + "upload/",
    registration:               API_BASE_URL + "registration/",
    logout:                     API_BASE_URL + "logout/",
    user:                       API_BASE_URL + "user/",
    changePassword:             API_BASE_URL + "password/change/",
    SMSRequest:                 API_BASE_URL + "sms-verification/request/",
    SMSVerify:                  API_BASE_URL + "sms-verification/verify/",
    categories:                 API_BASE_URL + "categories/",
    services:                   API_BASE_URL + "services/",
    checkemail:                 API_BASE_URL + "check-email/",
    checkphone:                 API_BASE_URL + "check-phone/",
    checkbankaccount:           API_BASE_URL + "check-bank-account/",
    hireservices:               API_BASE_URL + "hire-services/",
    cards:                      API_BASE_URL + "cards/",
    daysoff:                    API_BASE_URL + "days-off/",
    professionalsavailability:  API_BASE_URL + "professionals-availability/",
    devices:                    API_BASE_URL + "device/",
    coupon:                     API_BASE_URL + "coupon/",
    verifyEmail:                API_BASE_URL + "registration/resend-verify-email/",
}
