# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 11:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_iban.fields
import smsverification.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FIN', 'Final'), ('PRO', 'Professional')], default='FIN', max_length=20)),
                ('phone', models.CharField(max_length=20, validators=[smsverification.validators.validate_phone_number])),
                ('picture', models.URLField(blank=True, null=True)),
                ('swift_bank_account', django_iban.fields.SWIFTBICField(blank=True, max_length=11, null=True)),
                ('iban_bank_account', django_iban.fields.IBANField(blank=True, max_length=34, null=True)),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='Separate urls using a blank space', null=True, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('work_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_zones', to='geo.WorkZone', verbose_name='WorkZone')),
            ],
        ),
    ]
