# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 15:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='Separate urls using a comma space', null=True, size=None),
        ),
    ]
