# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171114_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
