# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]), blank=True, help_text='Separate using a comma', null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]), blank=True, help_text='Separate using a comma', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='Separate urls using a comma', null=True, size=None),
        ),
    ]
