# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20171130_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.IntegerField(blank=True, null=True, validators=[profiles.validators.validate_city]),
        ),
    ]
