# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
