# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 09:19
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True, validators=[profiles.validators.validate_city]), blank=True, help_text='Separate using a comma', null=True, size=None),
        ),
    ]
