# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cities',
            new_name='city',
        ),
    ]
