# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-05 06:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount_off', models.FloatField(help_text='Enter the amount of money to be deducted')),
                ('type', models.CharField(max_length=20)),
                ('redemption', models.DateTimeField(blank=True, null=True)),
                ('valid', models.BooleanField(default=True)),
                ('used_amount', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedGiftCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=0, max_length=50)),
                ('is_partial', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_gift_card', to='gift_card.GiftCard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usedgiftcard',
            unique_together=set([('coupon', 'transaction_id')]),
        ),
    ]
