# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-06 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gift_card.models


class Migration(migrations.Migration):

    dependencies = [
        ('gift_card', '0002_auto_20200806_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(default=gift_card.models.generate_primary_code, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='gifted_to',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='gifted_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='remaining_amount',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='type',
            field=models.CharField(default='MON', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='used_amount',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
