# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        ('services', '0002_userservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cities',
            field=models.ManyToManyField(to='geo.City'),
        ),
    ]
