# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20171124_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cities',
        ),
    ]
