# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20171201_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireservice',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('ACP', 'Accept'), ('CMP', 'Complete'), ('CAN', 'Cancel'), ('REJ', 'Reject')], default='PEN', max_length=3),
        ),
    ]
