# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 09:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20171220_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireservice',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
