# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20171222_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
