# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_auto_20171228_1254'),
        ('services', '0015_auto_20171228_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireservice',
            name='coupon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.Coupon'),
        ),
    ]
