# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields
import languages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_hireservice_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.CharField(blank=True, max_length=100, null=True),
        )
    ]
