# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 17:00
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import languages.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20180124_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityservices',
            name='vat_percent',
            field=models.FloatField(default=7.7),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='net_total',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=10),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='net_total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='vat',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=10),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='vat_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        )
    ]
