# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 09:19
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20180126_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='hireservice',
            name='net_charged',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=10),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='net_charged_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='total_charged',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=10),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='total_charged_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='vat_charged',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='CHF', max_digits=10),
        ),
        migrations.AddField(
            model_name='hireservice',
            name='vat_charged_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='cityservices',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('CHF', 'Swiss Franc')], default='CHF', editable=False, max_length=3),
        ),
    ]
