# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20180129_0919'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='category',
            name='language',
        ),
    ]
