# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20180221_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='cityservices',
            options={'ordering': ('service__order',)},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order',)},
        ),
    ]
